INSERT INTO people (name) VALUES ('Juan');
INSERT INTO people (name) VALUES ('Pedro');
INSERT INTO people (name) VALUES ('Andres');
INSERT INTO people (name) VALUES ('Alonso');
INSERT INTO people (name) VALUES ('Lucia');
INSERT INTO people (name) VALUES ('Pedro');
INSERT INTO people (name) VALUES ('Antonia');
INSERT INTO acquaintances (parent_id, related_id) VALUES (1,2);
INSERT INTO acquaintances (parent_id, related_id) VALUES (2,4);
INSERT INTO acquaintances (parent_id, related_id) VALUES (1,3);
INSERT INTO acquaintances (parent_id, related_id) VALUES (2,3);
INSERT INTO acquaintances (parent_id, related_id) VALUES (4,3);
INSERT INTO acquaintances (parent_id, related_id) VALUES (5,3);
INSERT INTO acquaintances (parent_id, related_id) VALUES (6,3);
INSERT INTO acquaintances (parent_id, related_id) VALUES (7,3);